In [27]:
from sklearn import metrics

In [28]:
import pickle

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from xgboost import XGBClassifier
df = pd.read_excel('Amazon_labels.xlsx')
df.head()

review_lemm label
0  well available mic price range mic connect dsl...   pos
1  hi mic month write review give genuine review ...   pos
2  product quality good bad build good thing want...   pos
3  record phone laptop quality regular headphone ...   pos
4  honest review boya m read help clear dilemma n...   pos

### Check for missing values

0       well available mic price range mic connect dsl...
1       hi mic month write review give genuine review ...
2       product quality good bad build good thing want...
3       record phone laptop quality regular headphone ...
4       honest review boya m read help clear dilemma n...
                              ...                        
4834              noise cancellation bad purchasenot good
4835                                         goodnot good
4836                                         goodnot good
4837                                good purchasenot good
4838                                    good worknot good
Name: review_lemm, Length: 4820, dtype: object

In [31]:
df.isnull().sum()

review_lemm    19
label           0
dtype: int64

In [32]:
df.dropna(inplace=True)

df.shape

(4820, 2)

In [33]:
from sklearn.model_selection import train_test_split

X = df['review_lemm']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [34]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB                    
from sklearn.svm import LinearSVC



# XGboost Classification

In [35]:
text_clf_xg = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', XGBClassifier()),
])

In [36]:
text_clf_xg.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='...
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=6, min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=100,
              

In [37]:
predictions = text_clf_xg.predict(X_test)

In [38]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[ 133   22   32]
 [   1  198   13]
 [  16   40 1136]]


In [39]:
print(metrics.accuracy_score(y_test,predictions))

0.9220615964802011


In [40]:
predictions

array(['pos', 'pos', 'neu', ..., 'neu', 'neg', 'pos'], dtype=object)

In [41]:
w=text_clf_xg.predict(['good product and i am really very happy happy using this'])

In [42]:
w

array(['pos'], dtype=object)

In [43]:
saved_xgb=pickle.dumps(text_clf_xg)

In [44]:
test_pickle=pickle.loads(saved_xgb)

In [45]:
y_pred=test_pickle.predict(X_test)

In [46]:
print(metrics.accuracy_score(y_test,y_pred))

0.9220615964802011


In [47]:
import pickle
pickle.dump(text_clf_xg,open('new_xgb_model.pkl','wb'))

In [56]:
test_pickle.predict([''])

array(['pos'], dtype=object)