In [46]:
from sklearn import metrics

In [47]:
import pickle

In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from xgboost import XGBClassifier
df = pd.read_excel('new_review_label.xlsx')
df.head()

Unnamed: 0                                            reviews label
0           0  i would say this is the best available mic in ...   pos
1           1  hi so after using this mic for about a month i...   pos
2           2  product quality was good not bad the build was...   pos
3           3  when recording on phone or laptop the quality ...   pos
4           4  i will give my honest review on boya m read th...   pos

### Check for missing values

In [50]:
df.isnull().sum()

Unnamed: 0     0
reviews       10
label          0
dtype: int64

In [51]:
df.dropna(inplace=True)

df.shape

(4829, 3)

In [59]:
from sklearn.model_selection import train_test_split

X = df['reviews']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [60]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB                    
from sklearn.svm import LinearSVC



# XGboost Classification

In [61]:
text_clf_xg = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', XGBClassifier()),
])

In [62]:
text_clf_xg.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='...
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=6, min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=100,
              

In [63]:
predictions = text_clf_xg.predict(X_test)

In [64]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[193  40  68]
 [ 13 169  42]
 [ 49  22 998]]


In [65]:
print(metrics.accuracy_score(y_test,predictions))

0.8531994981179423


In [66]:
predictions

array(['pos', 'neg', 'neg', ..., 'pos', 'pos', 'neu'], dtype=object)

In [67]:
w=text_clf_xg.predict(['good product and i am really very happy happy using this'])

In [68]:
w

array(['pos'], dtype=object)

In [69]:
saved_xgb=pickle.dumps(text_clf_xg)

In [70]:
test_pickle=pickle.loads(saved_xgb)

In [71]:
y_pred=test_pickle.predict(X_test)

In [72]:
print(metrics.accuracy_score(y_test,y_pred))

0.8531994981179423


In [73]:
import pickle
pickle.dump(text_clf_xg,open('new_xgb_model.pkl','wb'))

In [90]:
test_pickle.predict(['waste of time'])

array(['neg'], dtype=object)